name : testing Release production workflow
on: push
env:
    GATSBY_CPU_COUNT: 2
    GATSBY_ENV: production
    DIRECTUS_AUTH_TOKEN: ${{ secrets.DIRECTUS_AUTH_TOKEN }}
    GATSBY_ENV_CIO_SITE_ID: ${{ secrets.GATSBY_ENV_CIO_SITE_ID }}
jobs:
    lint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        environment: production
        
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              
            - name: fetch git tags
              run: |
                   git fetch --prune --unshallow --tags
                   git tag --format='%(creatordate:short)%09%(refname:strip=2)' --sort=creatordate | grep production | awk '{ print $2; }' | tail -1 > output.txt
                   GIT_TAG_NAME=`cat output.txt`
                   echo "git tag is ${GIT_TAG_NAME}
                   
            - name: Clone latest tag
              uses: actions/checkout@v2.3.1
              with:
               ref: ${GIT_TAG_NAME}
               
       
            - name: Set the value
              run: |
                   echo "$GIT_TAG_NAME"
                   
                   
                             
